# Generated by Django 3.2.16 on 2024-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Аккаунт активен'),
        ),
    ]
